export enum Availability {
  daily = "daily",
  weekly = "weekly",
  biweekly = "biweekly",
  monthly = "monthly",
  other = "other",
}

export enum Field {
  frontend = "Frontend",
  backend = "Backend",
  devOps = "DevOps",
  softskills = "Softskills",
}

export enum TechKnowHow {
  ada = "Ada",
  angular = "Angular",
  ai = "AI - machine learning",
  aws = "Cloud Computing AWS",
  azure = "Cloud Computing Azure",
  c = "C#",
  cplusplus = "C/C++",
  cobol = "Cobol",
  css = "CSS",
  dart = "Dart",
  dataanalysis = "Data analysis",
  delphi = "Delphi/Pascal",
  docker = "Docker",
  figma = "Figma",
  git = "Git/GitHub",
  go = "Go",
  google = "Cloud Computing Google Cloud",
  groovy = "Groovy",
  haskell = "Haskell",
  html = "HTML",
  java = "Java",
  javascript = "Javascript",
  julia = "Julia",
  kotlin = "Kotlin",
  kubernetes = "Kubernetes",
  linux = "Linux",
  lua = "Lua",
  matlab = "MATLAB",
  mongodb = "MongoDB",
  nodejs = "Node.js",
  nosql = "NoSQL",
  oracle = "Cloud Computing Oracle",
  pearl = "Pearl",
  php = "PHP",
  pm = "Project Managment",
  python = "Python",
  r = "R",
  react = "React.js",
  ruby = "Ruby",
  rust = "Rust",
  sass = "Sass",
  scala = "Scala",
  scrum = "Scrum",
  securitiy = "Cyber Security",
  sql = "SQL",
  swift = "Swift",
  typescript = "Typescript",
  ui = "UI",
  ux = "UX",
  vba = "Visual Basic for Applications",
  visualbasic = "Classic Visual Basic",
  vue = "Vue.js",
}

export enum TimeSlots {
  momo = "Monday morning",
  moaf = "Monday afternoon",
  moev = "Monday evening",
  tumo = "Tuesday morning",
  tuaf = "Tuesday afternoon",
  tuev = "Tuesday evening",
  wemo = "Wednesday morning",
  weaf = "Wednesday afternoon",
  weev = "Wednesday evening",
  thumo = "Thursday morning",
  thuaf = "Thursday afternoon",
  thuev = "Thursday evening",
  frimo = "Friday morning",
  friaf = "Friday afternoon",
  friev = "Friday evening",
  samo = "Saturday morning",
  saaf = "Saturday afternoon",
  saev = "Saturday evening",
  sumo = "Sunday morning",
  suaf = "Sunday afternoon",
  suev = "Sunday evening",
}
